// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 7dc4d5d85c
// Version Date: 2018年 5月28日 星期一 22时12分59秒 UTC

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "bookinfo/pb/comments"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC BookCommentsServer.
func MakeGRPCServer(endpoints Endpoints) pb.BookCommentsServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	return &grpcServer{
		// bookcomments

		post: grpctransport.NewServer(
			endpoints.PostEndpoint,
			DecodeGRPCPostRequest,
			EncodeGRPCPostResponse,
			serverOptions...,
		),
		get: grpctransport.NewServer(
			endpoints.GetEndpoint,
			DecodeGRPCGetRequest,
			EncodeGRPCGetResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the BookCommentsServer interface
type grpcServer struct {
	post grpctransport.Handler
	get  grpctransport.Handler
}

// Methods for grpcServer to implement BookCommentsServer interface

func (s *grpcServer) Post(ctx context.Context, req *pb.PostReq) (*pb.PostResp, error) {
	_, rep, err := s.post.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.PostResp), nil
}

func (s *grpcServer) Get(ctx context.Context, req *pb.GetReq) (*pb.GetResp, error) {
	_, rep, err := s.get.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.GetResp), nil
}

// Server Decode

// DecodeGRPCPostRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC post request to a user-domain post request. Primarily useful in a server.
func DecodeGRPCPostRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.PostReq)
	return req, nil
}

// DecodeGRPCGetRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC get request to a user-domain get request. Primarily useful in a server.
func DecodeGRPCGetRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.GetReq)
	return req, nil
}

// Server Encode

// EncodeGRPCPostResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain post response to a gRPC post reply. Primarily useful in a server.
func EncodeGRPCPostResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.PostResp)
	return resp, nil
}

// EncodeGRPCGetResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain get response to a gRPC get reply. Primarily useful in a server.
func EncodeGRPCGetResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.GetResp)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
