// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 7dc4d5d85c
// Version Date: 2018年 5月28日 星期一 22时12分59秒 UTC

package handlers

import (
	pb "bookinfo/pb/comments"
)

// Post implements Service.
func Post(IdPost int64, ContentPost string) (*pb.PostReq, error) {
	request := pb.PostReq{
		Id:      IdPost,
		Content: ContentPost,
	}
	return &request, nil
}

// Get implements Service.
func Get(IdGet int64) (*pb.GetReq, error) {
	request := pb.GetReq{
		Id: IdGet,
	}
	return &request, nil
}
