// Code generated by protoc-gen-go. DO NOT EDIT.
// source: details.proto

package details

/*
The package name determines the name of the directories that truss creates
for `package echo;` truss will create the directory "echo-service".
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import comments "bookinfo/pb/comments"
import _ "github.com/tuneinc/truss/deftree/googlethirdparty"

import (
	context "golang.org/x/net/context"
	newcontext "context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DetailReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailReq) Reset()         { *m = DetailReq{} }
func (m *DetailReq) String() string { return proto.CompactTextString(m) }
func (*DetailReq) ProtoMessage()    {}
func (*DetailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_details_6b264c97b7795ae3, []int{0}
}
func (m *DetailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailReq.Unmarshal(m, b)
}
func (m *DetailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailReq.Marshal(b, m, deterministic)
}
func (dst *DetailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailReq.Merge(dst, src)
}
func (m *DetailReq) XXX_Size() int {
	return xxx_messageInfo_DetailReq.Size(m)
}
func (m *DetailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailReq.DiscardUnknown(m)
}

var xxx_messageInfo_DetailReq proto.InternalMessageInfo

func (m *DetailReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DetailResp struct {
	Code                 int32           `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg                  string          `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Data                 *DetailRespData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DetailResp) Reset()         { *m = DetailResp{} }
func (m *DetailResp) String() string { return proto.CompactTextString(m) }
func (*DetailResp) ProtoMessage()    {}
func (*DetailResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_details_6b264c97b7795ae3, []int{1}
}
func (m *DetailResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailResp.Unmarshal(m, b)
}
func (m *DetailResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailResp.Marshal(b, m, deterministic)
}
func (dst *DetailResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailResp.Merge(dst, src)
}
func (m *DetailResp) XXX_Size() int {
	return xxx_messageInfo_DetailResp.Size(m)
}
func (m *DetailResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailResp.DiscardUnknown(m)
}

var xxx_messageInfo_DetailResp proto.InternalMessageInfo

func (m *DetailResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DetailResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *DetailResp) GetData() *DetailRespData {
	if m != nil {
		return m.Data
	}
	return nil
}

type DetailRespData struct {
	Id                   int32               `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name                 string              `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Intro                string              `protobuf:"bytes,3,opt,name=intro" json:"intro,omitempty"`
	Comments             []*comments.Comment `protobuf:"bytes,4,rep,name=comments" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *DetailRespData) Reset()         { *m = DetailRespData{} }
func (m *DetailRespData) String() string { return proto.CompactTextString(m) }
func (*DetailRespData) ProtoMessage()    {}
func (*DetailRespData) Descriptor() ([]byte, []int) {
	return fileDescriptor_details_6b264c97b7795ae3, []int{2}
}
func (m *DetailRespData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailRespData.Unmarshal(m, b)
}
func (m *DetailRespData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailRespData.Marshal(b, m, deterministic)
}
func (dst *DetailRespData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailRespData.Merge(dst, src)
}
func (m *DetailRespData) XXX_Size() int {
	return xxx_messageInfo_DetailRespData.Size(m)
}
func (m *DetailRespData) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailRespData.DiscardUnknown(m)
}

var xxx_messageInfo_DetailRespData proto.InternalMessageInfo

func (m *DetailRespData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DetailRespData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DetailRespData) GetIntro() string {
	if m != nil {
		return m.Intro
	}
	return ""
}

func (m *DetailRespData) GetComments() []*comments.Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func init() {
	proto.RegisterType((*DetailReq)(nil), "details.DetailReq")
	proto.RegisterType((*DetailResp)(nil), "details.DetailResp")
	proto.RegisterType((*DetailRespData)(nil), "details.DetailRespData")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookDetailsClient is the client API for BookDetails service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookDetailsClient interface {
	// Echo "echos" the incoming string
	Detail(ctx context.Context, in *DetailReq, opts ...grpc.CallOption) (*DetailResp, error)
}

type bookDetailsClient struct {
	cc *grpc.ClientConn
}

func NewBookDetailsClient(cc *grpc.ClientConn) BookDetailsClient {
	return &bookDetailsClient{cc}
}

func (c *bookDetailsClient) Detail(ctx context.Context, in *DetailReq, opts ...grpc.CallOption) (*DetailResp, error) {
	out := new(DetailResp)
	err := c.cc.Invoke(ctx, "/details.BookDetails/Detail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookDetailsServer is the server API for BookDetails service.
type BookDetailsServer interface {
	// Echo "echos" the incoming string
	Detail(newcontext.Context, *DetailReq) (*DetailResp, error)
}

func RegisterBookDetailsServer(s *grpc.Server, srv BookDetailsServer) {
	s.RegisterService(&_BookDetails_serviceDesc, srv)
}

func _BookDetails_Detail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookDetailsServer).Detail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/details.BookDetails/Detail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookDetailsServer).Detail(ctx, req.(*DetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookDetails_serviceDesc = grpc.ServiceDesc{
	ServiceName: "details.BookDetails",
	HandlerType: (*BookDetailsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detail",
			Handler:    _BookDetails_Detail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "details.proto",
}

func init() { proto.RegisterFile("details.proto", fileDescriptor_details_6b264c97b7795ae3) }

var fileDescriptor_details_6b264c97b7795ae3 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x51, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0xd3, 0x16, 0x50, 0x06, 0x25, 0xba, 0x9a, 0xd8, 0xe0, 0x4b, 0x53, 0x5f, 0x9a, 0x18,
	0xbb, 0x11, 0x6f, 0x20, 0x78, 0x81, 0xc6, 0x77, 0xb3, 0xed, 0x2e, 0x65, 0x03, 0xdd, 0x29, 0xdd,
	0xc1, 0x84, 0x57, 0xaf, 0xe0, 0xd1, 0xbc, 0x82, 0x07, 0x31, 0x6c, 0x01, 0x35, 0xfa, 0xf6, 0xcd,
	0xce, 0x9f, 0xf9, 0xff, 0x7f, 0xe1, 0x54, 0x2a, 0x12, 0x7a, 0x69, 0xd3, 0xba, 0x41, 0x42, 0x76,
	0xb4, 0x1b, 0x47, 0x93, 0x52, 0xd3, 0x7c, 0x9d, 0xa7, 0x05, 0x56, 0x9c, 0xd6, 0x46, 0x69, 0x53,
	0x70, 0x6a, 0xd6, 0xd6, 0x72, 0xa9, 0x66, 0xd4, 0x28, 0xc5, 0x4b, 0xc4, 0x72, 0xa9, 0x68, 0xae,
	0x1b, 0x59, 0x8b, 0x86, 0x36, 0x5c, 0x18, 0x83, 0x24, 0x48, 0xa3, 0xd9, 0x5d, 0x1b, 0xdd, 0xe4,
	0x88, 0x0b, 0x6d, 0x66, 0xc8, 0xeb, 0x9c, 0x17, 0x58, 0x55, 0xca, 0x90, 0x3d, 0x40, 0x2b, 0x8a,
	0xaf, 0xa1, 0x3f, 0x75, 0xa6, 0x99, 0x5a, 0xb1, 0x21, 0xf8, 0x5a, 0x86, 0x5e, 0xe4, 0x25, 0x41,
	0xe6, 0x6b, 0x19, 0xbf, 0x00, 0xec, 0x97, 0xb6, 0x66, 0x0c, 0x3a, 0x05, 0x4a, 0xe5, 0xf6, 0xdd,
	0xcc, 0x31, 0x3b, 0x83, 0xa0, 0xb2, 0x65, 0xe8, 0x47, 0x5e, 0xd2, 0xcf, 0xb6, 0xc8, 0x6e, 0xa1,
	0x23, 0x05, 0x89, 0x30, 0x88, 0xbc, 0x64, 0x30, 0xbe, 0x4a, 0xf7, 0x0d, 0xbf, 0x0f, 0x4d, 0x05,
	0x89, 0xcc, 0x89, 0xe2, 0x0d, 0x0c, 0x7f, 0xbf, 0xff, 0x88, 0xd0, 0xdd, 0x46, 0xd8, 0x9a, 0x1a,
	0x51, 0xa9, 0x9d, 0x83, 0x63, 0x76, 0x09, 0x5d, 0x6d, 0xa8, 0x41, 0xe7, 0xd1, 0xcf, 0xda, 0x81,
	0xdd, 0xc1, 0xf1, 0xbe, 0x5b, 0xd8, 0x89, 0x82, 0x64, 0x30, 0x3e, 0x4f, 0x0f, 0x65, 0x27, 0x2d,
	0x64, 0x07, 0xc9, 0xf8, 0x19, 0x06, 0x8f, 0x88, 0x8b, 0xd6, 0xde, 0xb2, 0x27, 0xe8, 0xb5, 0xc8,
	0xd8, 0x9f, 0xc8, 0xab, 0xd1, 0xc5, 0x3f, 0x35, 0x62, 0xf6, 0xf6, 0xf1, 0xf9, 0xee, 0x9f, 0x30,
	0xe0, 0xaf, 0xf7, 0xbc, 0xdd, 0xe7, 0x3d, 0xf7, 0xab, 0x0f, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xa3, 0xf1, 0x87, 0xd1, 0xd9, 0x01, 0x00, 0x00,
}
