// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 7dc4d5d85c
// Version Date: 2018年 5月28日 星期一 22时12分59秒 UTC

// Package grpc provides a gRPC client for the BookComments service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	"bookinfo/bookcomments-service/svc"
	pb "bookinfo/pb/comments"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.BookCommentsServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var postEndpoint endpoint.Endpoint
	{
		postEndpoint = grpctransport.NewClient(
			conn,
			"comments.BookComments",
			"Post",
			EncodeGRPCPostRequest,
			DecodeGRPCPostResponse,
			pb.PostResp{},
			clientOptions...,
		).Endpoint()
	}

	var getEndpoint endpoint.Endpoint
	{
		getEndpoint = grpctransport.NewClient(
			conn,
			"comments.BookComments",
			"Get",
			EncodeGRPCGetRequest,
			DecodeGRPCGetResponse,
			pb.GetResp{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		PostEndpoint: postEndpoint,
		GetEndpoint:  getEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCPostResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC post reply to a user-domain post response. Primarily useful in a client.
func DecodeGRPCPostResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.PostResp)
	return reply, nil
}

// DecodeGRPCGetResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC get reply to a user-domain get response. Primarily useful in a client.
func DecodeGRPCGetResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.GetResp)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCPostRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain post request to a gRPC post request. Primarily useful in a client.
func EncodeGRPCPostRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.PostReq)
	return req, nil
}

// EncodeGRPCGetRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain get request to a gRPC get request. Primarily useful in a client.
func EncodeGRPCGetRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.GetReq)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
